"""Remove bank details from User model

Revision ID: 1b9849a40f8b
Revises: 7acdae81f803
Create Date: 2025-07-02 17:51:53.154838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9849a40f8b'
down_revision = '7acdae81f803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
